# Generated by Django 4.1 on 2022-09-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "title",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=250)),
                ("image", models.ImageField(upload_to="apptaller2/images/")),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
